- name: Создать постгрес пользователя
  become: true
  ansible.builtin.user:
    name: "{{ postgresql_user }}"
    system: true
    state: present
    create_home: false

- name: Скачать источники постгре
  ansible.builtin.get_url:
    url: "{{ postgresql_url }}"
    mode: "0644"
    dest: "/tmp/{{ postgresql_archive_name }}"

- name: Разархивировать архив
  ansible.builtin.command:
    cmd: "tar -xzf /tmp/{{ postgresql_archive_name }} -C /tmp/"
  args:
    creates: "/tmp/{{ postgresql_dir_name }}"

- name: Создать директорию prefix
  become: true
  ansible.builtin.file:
    name: "{{ postgresql_prefix }}"
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: Настроить
  ansible.builtin.command:
    cmd: "./configure --prefix={{ postgresql_prefix }}"
    chdir: "/tmp/{{ postgresql_dir_name }}"
  args:
    creates: "{{ postgresql_prefix }}/bin/postgres"

- name: Собрать
  become: true
  ansible.builtin.command:
    cmd: "make -j{{ ansible_facts[']processor_vcpus'] | default(2) }}"
    chdir: "/tmp/{{ postgresql_dir_name }}"
  args:
    creates: "/tmp/{{ postgresql_dir_name }}/src/backend/postgres"

- name: Установить
  become: true
  ansible.builtin.command:
    cmd: "make install"
    chdir: "/tmp/{{ postgresql_dir_name }}"
  args:
    creates: "{{ postgresql_prefix }}/bin/postgres"

- name: Создать директорию для данных
  become: true
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0700"

- name: Инициализировать дб
  become: true
  ansible.builtin.command:
    cmd: "sudo -u {{ postgresql_user }} {{ postgresql_prefix }}/bin/initdb -D {{ postgresql_data_dir }}"
  args:
    creates: "{{ postgresql_data_dir }}/PG_VERSION"

- name: Настроить pg_hba.conf
  become: true
  ansible.builtin.copy:
    src: files/pg_hba.conf
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0600"
  notify: Restart postgresql

- name: Создать системд сервис
  become: true
  ansible.builtin.template:
    src: templates/postgresql.service.j2
    dest: /etc/systemd/system/postgresql.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Daemon-reload
    - Restart postgresql
