- name: Установить nginx
  become: true
  ansible.builtin.dnf:
    name: "nginx-{{ nginx_package_version }}"
    state: present

- name: Включить и запустить nginx.service
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Сгенерировать index.html
  become: true
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

# Для дебага
- name: Узнать версию nginx
  ansible.builtin.command: /usr/sbin/nginx -version
  register: nginx_version_result
  changed_when: false
  failed_when: false
  check_mode: false

- name: Подготовить дебаг сводку
  ansible.builtin.set_fact:
    nginx_debug:
      nginx_version: "{{ nginx_version_result | regex_findall('nginx/(\\S+)') | first | default('Неизвестно') }}"
      access_log: "/var/log/nginx/access.log"
      error_log: "/var/log/nginx/error.log"

- name: Вывести дебаг сводку
  ansible.builtin.debug:
    var: nginx_debug
