- name: Установка chrony на ntp server
  hosts: ntp
  roles:
    - role: chrony

- name: Установка nginx на app server
  hosts: app
  roles:
    - role: nginx

- name: Установка postgresql на db server
  hosts: db
  roles:
    - role: postgresql
