- name: Установить chrony
  become: true
  ansible.builtin.dnf:
    name: "chrony-{{ chrony_package_version }}"
    state: present

- name: Сгенировать chrony.conf для ntp server'a
  become: true
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chronyd
